name: Build Firmware

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_build_tools:latest

    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: true

    - name: Checkout Your Keyboard
      uses: actions/checkout@v3
      with:
        path: keyboards/gg69_iso

    - name: Prepare Files
      run: |
        cd keyboards/gg69_iso
        # Wir schieben deine Dateien an die richtige Stelle
        mkdir -p keymaps/via
        cp keymap.c keymaps/via/keymap.c

    - name: Compile
      run: |
        qmk compile -kb gg69_iso -km via

    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with:
        name: GG69_Firmware
        path: |
          *.bin
          *.hex
